git:
  tagName: v${version}
  commitMessage: Release v${version}
# https://github.com/release-it/release-it/blob/master/docs/recipes/auto-changelog.md
  changelog: npx auto-changelog --stdout --commit-limit false --unreleased --template https://raw.githubusercontent.com/cursormove/flow-is-helpers/master/__config__/scripts/changelog-preview.hbs
#../changelog.hbs
  beforeChangelogCommand: auto-changelog
  requireCommits: true
github:
  release: true
  releaseName: Broken link checker v${version}
hooks:
  after:release: npx auto-changelog --commit-limit false --template ../keepachangelog.hbs
