name: 'My Markdown Linter'
description: 'Lint Markdown files'
author: 'ruzickap'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'list'
  color: 'blue'
inputs:
  config_file:
    description: 'markdownlint config file'
  debug:
    description: 'Debug mode'
  exclude:
    description: 'Exclude files or directories'
  fd_cmd_params:
    description: 'Command line parameters for fd command'
  rules:
    description: 'Custom rule files for markdownlint'
  search_paths:
    description: 'Set paths which should be recursively scanned for markdown files (*.md) and linted'
