name: 'Broken Link Checker'
description: 'Broken link checker for web pages located localy or remotely'
author: 'ruzickap'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'list'
  color: 'blue'
inputs:
  debug:
    description: 'Debug mode (set -x)'
    required: false
    default: ''
  cmd_params:
    description: 'Command line parametrs for muffet'
    required: false
    default: ''
  pages_path:
    description: 'Realive path to the directory with local web pages'
    required: false
    default: ''
  run_timeout:
    description: 'Max number of seconds which URL checker can be running'
    required: false
    default: '300'
  url:
    description: 'URL which will be checked'
    required: true
    default: ''
outputs:
  output:
    description: 'Output of the link checker'
