---
# handlers file for my_common_defaults

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: reload snmpd
  service:
    name: snmpd
    state: restarted

- name: generate grub configuration
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
