name: build - vagrantcloud

on:
  push:
  # repository_dispatch:

env:
  PACKER_IMAGES_OUTPUT_DIR: /var/tmp/packer-templates-images
  PACKER_CACHE_DIR: /var/tmp/packer_cache
  LOGDIR: /var/tmp/packer-templates-logs
  VAGRANT_CLOUD_USER: peru
  TEST_SECRET: ${{ secrets.test_secret }}

jobs:

##############
# libvirt
##############

  build-libvirt:
    name: "*"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        stage:
          - windows-server-2012_r2-standard-x64-eval-libvirt
          - my_centos-7-x86_64-libvirt
          - my_ubuntu-18.04-server-amd64-libvirt
          - ubuntu-16.04-server-amd64-libvirt
          - ubuntu-18.04-server-amd64-libvirt
          - ubuntu-19.10-desktop-amd64-libvirt
          - ubuntu-18.04-desktop-amd64-libvirt
          - my_windows-10-enterprise-x64-eval-libvirt
          - windows-10-enterprise-x64-eval-libvirt
          - windows-server-2016-standard-x64-eval-libvirt
          - windows-server-2019-datacenter-x64-eval-libvirt

    steps:
      - name: Check if image is not already built
        run: |
          BUILD="${{ matrix.stage }}"
          PACKER_VAGRANT_PROVIDER="${BUILD##*-}"
          NAME="${BUILD%-*}"
          BOX_VERSION="$(date +%Y%m%d).01"
          echo "*** https://vagrantcloud.com/${VAGRANT_CLOUD_USER}/boxes/${NAME}/versions/${BOX_VERSION}/providers/${PACKER_VAGRANT_PROVIDER}.box"
          if curl -L --fail --silent --head --output /dev/null "https://vagrantcloud.com/${VAGRANT_CLOUD_USER}/boxes/${NAME}/versions/${BOX_VERSION}/providers/${PACKER_VAGRANT_PROVIDER}.box"; then
            echo "*** ${BUILD} exists on Vagrant Cloud"
            echo "::set-env name=skip::true"
          fi

      - name: Date ${{ matrix.stage }}
        if: env.skip == true
        run: |
          date
          echo $PACKER_IMAGES_OUTPUT_DIR

      - name: Test ${{ matrix.stage }}
        if: env.skip
        run: |
          echo "test 1234"
          echo $PACKER_IMAGES_OUTPUT_DIR
          echo $TEST_SECRET
