name: build - artifacts

on:
  push:
  # repository_dispatch:

env:
  MYTMP: /tmp

jobs:

##############
# libvirt
##############

  build-libvirt:
    name: "*"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        stage:
          - windows-server-2012_r2-standard-x64-eval-libvirt
          - my_centos-7-x86_64-libvirt

    steps:
      - name: Check if image is not already built
        run: |
          echo "`date` ${{ matrix.stage }}" >> /tmp/${{ matrix.stage }}.log

      - name: Upload ${{ env.MYTMP }}/${{ matrix.stage }}.log
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.stage }}.log
          path: ${{ env.MYTMP }}/${{ matrix.stage }}.log

      - name: Check if image is not already built
        run: rm -v ${{ env.MYTMP }}/${{ matrix.stage }}.log

      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: ${{ matrix.stage }}.log
          path: ${{ env.MYTMP }}

      - name: Print the final result
        shell: bash
        run: cat ${{ env.MYTMP }}/${{ matrix.stage }}.log

      - name: Download non-existing ${{ env. }}
        uses: actions/download-artifact@v1
        with:
          name: does_not_exist.log
          path: /tmp/
