name: command-checks

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - README.md
  push:
    paths:
      - README.md
    branches:
      - master

jobs:
  command-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Check commands in README.md file
        run: sed -n '/^```bash.*/,/^```$/p' README.md | sed '/^```*/d' | bash -x
