name: check-broken-links

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/check-broken-links.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/check-broken-links.yml

jobs:
  my-broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Broken link checker
        run: |
          export INPUT_URL="https://google.com"
          export INPUT_CMD_PARAMS="--verbose --buffer-size=8192 --max-connections=10 --color=always --one-page-only"
          wget -qO- https://github.com/raviqqe/muffet/releases/download/v2.2.1/muffet_2.2.1_Linux_x86_64.tar.gz | sudo tar xzf - -C /usr/local/bin/ muffet
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v2/entrypoint.sh | bash
