name: check-resources

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/check-resources.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/check-resources.yml

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Show resources
        run: |
          set -x
          sysctl -n hw.ncpu
          system_profiler SPHardwareDataType
          top -l 1 -s 0 | grep PhysMem
          df -h
          diskutil list
          diskutil info disk0
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Show resources
        run: |
          sudo apt update &> /dev/null
          sudo apt install -y lshw &> /dev/null
          set -x
          df -h
          free -h
          egrep -wo 'vmx|lm|aes' /proc/cpuinfo  | sort | uniq | sed -e 's/aes/Hardware encryption=Yes (&)/g' -e 's/lm/64 bit cpu=Yes (&)/g' -e 's/vmx/Intel hardware virtualization=Yes (&)/g'
          lshw
