name: docker-image

on:
  push:
    paths:
      - Dockerfile
      - .dockerignore
      - .hadolint.yaml
      - entrypoint.sh
      - .github/workflows/docker-image.yml

jobs:
  docker-build-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build test
        run: |
          docker build . --file Dockerfile

  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        run: shellcheck ./entrypoint.sh

  hadolint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: hadolint
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .
