name: gh-action-test

on:
  push:
  # repository_dispatch:

jobs:
  gh-action-test:
    runs-on: ubuntu-18.04

    steps:
      - uses: ruzickap/action-test
        with:
          exclude: |
            test12
            test345
            test567
