name: gh-action-test

on:
  # push:
  # repository_dispatch:
  schedule:
    - cron: '0 15 1 1 0'

jobs:
  gh-action-test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ruzickap/action-test@master
        with:
          exclude: ./create_pr.sh
