name: gh-action-test

on:
  push:
  # repository_dispatch:

jobs:
  gh-action-test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: ruzickap/action-test@master
        with:
          exclude: |
            ./entrypoint.sh
            */tests/*
