name: gh-pages

on:
  # push:
  # repository_dispatch:
  schedule:
    - cron: '0 15 1 1 0'

jobs:
  gh-pages:
    runs-on: ubuntu-18.04

    steps:
      - name: Create web page
        run: |
          mkdir public
          #echo test3.xvx.cz > public/CNAME
          echo '<a href="https://xvx.cz/">https://xvx.cz/</a>' > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
