name: gh-pages

on:
  push:

jobs:
  gh-pages:
    runs-on: ubuntu-18.04

    steps:
      - name: Create web page
        run: |
          mkdir public
          echo test.xvx.cz > public/CNAME
          echo '<a href="https://xvx.cz/">xvx.cz</a>' > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.8.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
        with:
          forceOrphan: true
