name: mac-test

on:
  repository_dispatch:
  #schedule:
  #    - cron: '0 15 1 1 0'
  # pull_request:
  #   types: [opened, synchronize]
  #   paths:
  #     - tasks/**
  #     - .github/workflows/mac-test.yml
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - tasks/**
  #     - .github/workflows/mac-test.yml

jobs:
  mac-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ansible packages
        run: |
          pip3 install --user ansible
          ln -s /Users/runner/Library/Python/3.7/bin/ansible /usr/local/bin/ansible
          ln -s /Users/runner/Library/Python/3.7/bin/ansible-playbook /usr/local/bin/ansible-playbook

      - name: Run Ansible
        run: |
          ./run_ansible_macos_workstation.sh
