name: mac-test

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/mac-test.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/mac-test.yml

jobs:
  mac-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ansible packages
        run: |
          pip install --user ansible
          pip install pywinrm
          ln -s /Users/runner/Library/Python/2.7/bin/ansible /usr/local/bin/ansible
          ln -s /Users/runner/Library/Python/2.7/bin/ansible-playbook /usr/local/bin/ansible-playbook
          which python3

      - name: Run Ansible
        run: |
          ./run_ansible_macos_workstation.sh
