name: mac-fedora

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/mac-fedora.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/mac-fedora.yml

jobs:
  mac-fedora:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Checks
      #   run: |
      #     set -x
      #     top -l 1 -s 0 | grep PhysMem
      #     df -h .

      - name: Install Ansible packages
        run: |
          brews install ansible gnu-sed
          # pip3 install --user ansible
          # ln -s /Users/runner/Library/Python/3.7/bin/ansible /usr/local/bin/ansible
          # ln -s /Users/runner/Library/Python/3.7/bin/ansible-playbook /usr/local/bin/ansible-playbook

      - name: Stat Fedora VirtualBox VM
        env:
          RAM: 4096
        run: |
          set -x
          vagrant init fedora/32-cloud-base
          sed -i '/^Vagrant.configure/a \ \ config.vm.provider "virtualbox" do |vb|\n \ \ \ \ vb.memory = "4096"\n \ end' Vagrantfile
          vagrant up

      # - name: Add main user to Fedora VirtualBox VM
      #   run: |
      #     ansible --become --user vagrant --extra-vars "ansible_password=vagrant ansible_port=2222" -m user -a "name=${MYUSER} password={{ \"${PASSWORD}\" | password_hash('sha512') }} append=yes groups=wheel" -i "127.0.0.1," 127.0.0.1

      # - name: Ansible
      #   run: |
      #     ansible-playbook --user="${MYUSER}" --extra-vars "ansible_password=${PASSWORD} ansible_become_password=${PASSWORD} ansible_port=2222" main.yml -i "127.0.0.1,"
