name: mac-fedora

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/mac-fedora.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/mac-fedora.yml

jobs:
  mac-fedora:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fedora
        run: |
          brew cask install vagrant
          vagrant init fedora/32-cloud-base
          vagrant up
          ansible-playbook --diff --user="vagrant" --extra-vars "ansible_password=vagrant ansible_become_password=vagrant ansible_port=2222" main.yml -i "127.0.0.1,"
