name: my_centos

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/my_centos.yml
      - ansible/roles/ansible-role-my_common_defaults/**
      - ansible/site.yml
      - build.sh
      - my_centos-7.json
      - scripts/linux-common/**
      - vagrant_init_destroy_boxes.sh
      - Vagrantfile-linux.template
  push:
    branches:
      - master
    paths:
      - .github/workflows/my_centos.yml
      - ansible/roles/ansible-role-my_common_defaults/**
      - ansible/site.yml
      - build.sh
      - my_centos-7.json
      - scripts/linux-common/**
      - vagrant_init_destroy_boxes.sh
      - Vagrantfile-linux.template

env:
  ACCELERATOR: hvf

jobs:
  my_centos:
    name: "*"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        stage:
          - my_centos-7-x86_64-virtualbox
          - my_centos-7-x86_64-libvirt
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install packages
        run: |
          brew install ansible coreutils gnu-sed packer qemu

      - name: Build image - ${{ matrix.stage }}
        run: |
          export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:${PATH}
          ./build.sh ${{ matrix.stage }}

      - name: Check the created box image - ${{ matrix.stage }}
        if: ${{ contains( matirx.stage, 'virtualbox' ) }}
        run: |
          export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:${PATH}
          ./vagrant_init_destroy_boxes.sh /var/tmp/packer-templates-images/${{ matrix.stage }}.box
