name: my_ubuntu-server

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/my_ubuntu-server.yml
      - my_ubuntu-server.json
      - Vagrantfile-linux.template
      - build.sh
      - templates/my_ubuntu.md
      - scripts/ubuntu/**
      - scripts/linux-common/**
      - http/ubuntu-server/**
      - ansible/site.yml
      - ansible/roles/ansible-role-my_common_defaults/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/my_ubuntu-server.yml
      - my_ubuntu-server.json
      - Vagrantfile-linux.template
      - build.sh
      - templates/ubuntu.md
      - scripts/ubuntu/**
      - scripts/linux-common/**
      - http/ubuntu-server/**
      - ansible/site.yml
      - ansible/roles/ansible-role-my_common_defaults/**

jobs:
  my_ubuntu-server:
    name: "*"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        stage:
          - my_ubuntu-20.04-server-amd64-virtualbox
          - my_ubuntu-18.04-server-amd64-virtualbox
          - my_ubuntu-16.04-server-amd64-virtualbox
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install packages
        run: |
          brew install ansible coreutils gnu-sed packer

      - name: Build image - ${{ matrix.stage }}
        run: |
          export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:${PATH}
          ./build.sh ${{ matrix.stage }}

      - name: Check the created box image - ${{ matrix.stage }}
        run: |
          export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:${PATH}
          ./vagrant_init_destroy_boxes.sh /var/tmp/packer-templates-images/${{ matrix.stage }}.box
