name: my_windows

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/my_windows.yml
      - ansible/roles/ansible-role-virtio-win/**
      - ansible/win-simple.yml
      - build.sh
      - http/windows-10/**
      - scripts/win-common/**
      - Vagrantfile-windows.template
      - win_iso.sha256
      - my_windows.json
  push:
    branches:
      - master
    paths:
      - .github/workflows/my_windows.yml
      - ansible/roles/ansible-role-virtio-win/**
      - ansible/win-simple.yml
      - build.sh
      - http/windows-10/**
      - scripts/win-common/**
      - Vagrantfile-windows.template
      - win_iso.sha256
      - my_windows.json

env:
  ACCELERATOR: hvf
  # https://github.com/ansible/ansible/issues/32499
  OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES

jobs:
  my_windows:
    name: "*"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        stage:
          - my_windows-10-enterprise-x64-eval-virtualbox
          - my_windows-10-enterprise-x64-eval-libvirt
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install packages
        run: |
          brew install ansible coreutils gnu-sed packer qemu
          pip3 install pywinrm

      - name: Build image - ${{ matrix.stage }}
        run: |
          export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:${PATH}
          ./build.sh ${{ matrix.stage }}

      - name: Check the created box image - ${{ matrix.stage }}
        if: contains( matrix.stage, 'virtualbox' )
        run: |
          export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:${PATH}
          ./vagrant_init_destroy_boxes.sh /var/tmp/packer-templates-images/${{ matrix.stage }}.box
