name: mytest

on:
  push:

jobs:
  myenv:
    runs-on: ubuntu-18.04
    needs: shellcheck
    steps:
      - name: Test
        run: echo "::set-env name=color::yellow"

      - name: Test - shell env
        run: echo "${color}"

      - name: Test 2 - global env
        run: echo "${{env.color}}"

  mytest:
    runs-on: ubuntu-18.04
    needs:
      - myenv
    steps:
      - name: Test
        run: echo "${{ github.actor }} | ${{ github.repository }}"

      - name: Good
        run: echo "${GITHUB_REPOSITORY%/*} | ${GITHUB_REPOSITORY##*/} | ${GITHUB_REPOSITORY}"

      - name: Test2
        env:
          T1: "${GITHUB_REPOSITORY%/*}"
          T2: "${GITHUB_REPOSITORY##*/}"
          T3: "${GITHUB_REPOSITORY}"
        run: echo "${T1} | ${T2} | ${T3} | ${color} | ${{env.color}}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Dump GitHub context2
        env:
          GITHUB_CONTEXT: ${{ github.event.repository.name }}
          GITHUB_CONTEXT2: ${{ github.event.repository.owner.name }}
        run: echo "| ${GITHUB_CONTEXT} | ${GITHUB_CONTEXT2}"

      - name: Deploy
        if: github.event_name == 'push'
        run: echo "Run only in case of push to master (not PR)"
