name: new-markdown-checks

on:
  push:
    paths:
      - '**.md'
      - .github/workflows/new-markdown-checks.yml
      - .markdownlint.yml

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: .markdownlint.yml
          ignore: CHANGELOG.md
          args: '**.md'
