name: periodic-broken-links-check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/periodic-broken-links-check.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/periodic-broken-links-check.yml

jobs:
  broken-link-checker:
    runs-on: ubuntu-18.04
    steps:
      - name: Broken link checker
        env:
          EXCLUDE: |
            github.com/ruzickap/environment-mylabs-
            github.com/ruzickap/front-end
            github.com/ruzickap/k8s-flux-repository
            linkedin.com
            localhost
            myexample.dev
            mylabs.dev
        run: |
          set -x
          export INPUT_URL="https://ruzickap.github.io/k8s-sockshop"
          export INPUT_CMD_PARAMS="--verbose --buffer-size=8192 --concurrency=10 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))"
          echo "${INPUT_CMD_PARAMS}"
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-broken-link-checker/v1/entrypoint.sh | bash

      - name: Broken link checker 2
        env:
          EXCLUDE: |
            github.com/ruzickap/environment-mylabs-
            github.com/ruzickap/front-end
            github.com/ruzickap/k8s-flux-repository
            linkedin.com
            localhost
            myexample.dev
            mylabs.dev
        run: |
          export INPUT_URL="https://ruzickap.github.io/k8s-harbor"
          export INPUT_CMD_PARAMS="--verbose --buffer-size=8192 --concurrency=10 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))"
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-broken-link-checker/v1/entrypoint.sh | bash

      - name: Broken link checker 3
        env:
          EXCLUDE: |
            github.com/ruzickap/environment-mylabs-
            github.com/ruzickap/front-end
            github.com/ruzickap/k8s-flux-repository
            linkedin.com
            localhost
            myexample.dev
            mylabs.dev
        run: |
          export INPUT_URL="https://ruzickap.github.io/k8s-flux-istio-gitlab-harbor"
          export INPUT_CMD_PARAMS="--verbose --buffer-size=8192 --concurrency=10 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))"
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-broken-link-checker/v1/entrypoint.sh | bash

      - name: Broken link checker 3
        env:
          EXCLUDE: |
            github.com/ruzickap/environment-mylabs-
            github.com/ruzickap/front-end
            github.com/ruzickap/k8s-flux-repository
            linkedin.com
            localhost
            myexample.dev
            mylabs.dev
        run: |
          export INPUT_URL="https://awsug.cz"
          export INPUT_CMD_PARAMS="--verbose --buffer-size=8192 --concurrency=10 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))"
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-broken-link-checker/v1/entrypoint.sh | bash
