name: remote_build_server

on:
  push:
    paths:
      - tools/create_remote_build_server/**
      - .github/workflows/remote_build_server.yml

jobs:
  remote_build_server-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create ssh key and add it to authorized keys
        run: |
          chmod 0700 /home/$USER
          install -m 0700 -d $HOME/.ssh && ssh-keygen -b 2048 -t rsa -f $HOME/.ssh/id_rsa -q -N ""
          cp $HOME/.ssh/id_rsa.pub $HOME/.ssh/authorized_keys
          chmod 0600 $HOME/.ssh/authorized_keys

      - name: Install Ansible packages
        run: |
          sudo apt update
          sudo apt install -y python-jmespath

      - name: Run ansible
        run: |
          export REMOTE_USER="${USER}"
          export REMOTE_IP="localhost"
          export ANSIBLE_TAGS_SKIP="actions-runner_registration"
          export TAGS_SKIP="actions-runner_registration"
          cd tools/create_remote_build_server
          ./build_remote_ssh_ubuntu.sh
