name: remote_build_server

on:
  push:
    paths:
      - tools/create_remote_build_server/**
      - .github/workflows/remote_build_server.yml

jobs:
  remote_build_server-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run find
        env:
          REMOTE_IP: 127.0.0.1
        run: |
          cd tools/create_remote_build_server
          ./build_remote_ssh_ubuntu.sh
