name: remote_build_server

on:
  push:
    paths:
      - tools/create_remote_build_server/**
      - .github/workflows/remote_build_server.yml

jobs:
  remote_build_server-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create ssh key and add it to authorized keys
        run: |
          install -m 0700 -d $HOME/.ssh && ssh-keygen -b 2048 -t rsa -f $HOME/.ssh/id_rsa -q -N ""
          cp $HOME/.ssh/id_rsa.pub $HOME/.ssh/authorized_keys
          chmod 0600 $HOME/.ssh/authorized_keys
          find ~/.ssh -ls
          whoami && id
          ssh -v ${USER}@127.0.0.1 uptime

      - name: Run ansible
        env:
          REMOTE_IP: 127.0.0.1
        run: |
          export REMOTE_USER="${USER}"
          cd tools/create_remote_build_server
          ./build_remote_ssh_ubuntu.sh
