name: remote_build_server

on:
  push:
    paths:
      - tools/create_remote_build_server/
      - .github/workflows/remote_build_server.yml

jobs:
  remote_build_server-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run find
        run: find . -type d
