name: example-client-payload-action
on: repository_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          set -x
          echo "field: ${{ github.event.client_payload.foo }}"
          echo "payload: ${{ toJson(github.event.client_payload) }}"
          echo '${{ toJson(github.event.client_payload) }}' | jq
      - run: |
          set -x
          cat << EOF
          ${{ toJson(github.event.client_payload) }}
          EOF
      - run: |
          set -x
          cat << EOF | jq
          ${{ toJson(github.event.client_payload) }}
          EOF
