name: example-client-payload-action
on: repository_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "field: ${{ github.event.client_payload.foo }}"
          echo "payload: ${{ toJson(github.event.client_payload) }}"
          echo '${{ toJson(github.event.client_payload) }}'
          echo '${{ toJson(github.event.client_payload) }}' | jq
          echo "payload-whole: ${{ github.event.client_payload }}"
