name: example-client-payload-action
on: repository_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          set -x
          brew update
          brew upgrade jq
          echo '{}' | jq
          echo "field: ${{ github.event.client_payload.foo }}"
          echo "payload: ${{ toJson(github.event.client_payload) }}"
          echo '${{ toJson(github.event.client_payload) }}' | jq
      - name: test2
        run: |
          set -x
          cat << EOF
          ${{ toJson(github.event.client_payload) }}
          EOF
      - name: test3
        run: |
          set -x
          cat << EOF | jq
          ${{ toJson(github.event.client_payload) }}
          EOF
