on:
  schedule:
    - cron: "18 17 * * *"

name: Check markdown links
jobs:
  broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-18.04
    steps:
    - name: Check
      uses: ruzickap/action-broken-link-checker@v1
      env:
        URL: https://www.google.com

    - uses: actions/checkout@v2

    - name: Check simple
      env:
        URL: https://my-testing-domain.com
        PAGES_PATH: ./tests/
        MUFFET_CMD_PARAMS: --skip-tls-verification
      run: |
        wget https://raw.githubusercontent.com/ruzickap/action-broken-link-checker/v1/entrypoint.sh
        bash ./entrypoint.sh
