on:
  schedule:
    - cron: '0 0 * * 0'

name: Check broken links
jobs:
  broken-link-checker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Check - container
        uses: ruzickap/action-test@v1
        with:
          cmd_params: "--verbose --ignore-fragments --one-page-only"
          url: https://google.com

      - name: Check - simple
        env:
          INPUT_CMD_PARAMS: "--verbose --ignore-fragments --one-page-only"
          INPUT_URL: https://google.com
        run: |
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-test/v1/entrypoint.sh | bash

      - name: Check - simple - local pages
        env:
          INPUT_CMD_PARAMS: "--skip-tls-verification --verbose"
          INPUT_URL: https://my-testing-domain.com
          INPUT_PAGES_PATH: ./tests/
        run:
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-test/v1/entrypoint.sh | bash
