on:
  schedule:
    - cron: '43 18 * * *'

name: Check broken links
jobs:
  broken-link-checker:
    name: Check broken links - google.com
    runs-on: ubuntu-18.04
    steps:
    - name: Check - container
      uses: ruzickap/action-test@v1
      env:
        URL: https://google.com

    - name: Check - simple
      env:
        URL: https://google.com
      run: |
        wget https://raw.githubusercontent.com/ruzickap/action-test/v1/entrypoint.sh
        bash ./entrypoint.sh

    - uses: actions/checkout@v2

    - name: Check - simple - local pages
      env:
        URL: https://my-testing-domain.com
        PAGES_PATH: ./tests/
        MUFFET_CMD_PARAMS: --skip-tls-verification
      run: |
        wget https://raw.githubusercontent.com/ruzickap/action-test/v1/entrypoint.sh
        bash ./entrypoint.sh
