name: shellcheck

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.sh'
  push:
    paths:
      - '**.sh'
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
