name: shellcheck

on:
  repository_dispatch:
#  pull_request:
#    types: [opened, synchronize]
#    paths:
#      - '**.sh'
#      - .github/workflows/shellcheck.yml
#  push:
#    branches:
#      - master
#    paths:
#      - '**.sh'
#      - .github/workflows/shellcheck.yml

jobs:
  shellcheck-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Lint check
        uses: azohra/shell-linter@latest
