name: shellcheck

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.sh'
  push:
    paths:
      - '**.sh'

jobs:
  shellcheck-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Lint check
        uses: azohra/shell-linter@v0.2.0
