name: shellcheck

on:
  push:
    paths:
      - '**.sh'
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
