name: tests

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - tests/**
      - .github/workflows/tests.yml
      - entrypoint.sh
      - Dockerfile
      - .dockerignore
  push:
    paths:
      - tests/**
      - .github/workflows/tests.yml
      - entrypoint.sh
      - Dockerfile
      - .dockerignore
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        run: shellcheck tests/*.sh

  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./run_tests.sh
        working-directory: ./tests
