name: tests

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        run: shellcheck tests/run_tests.sh

  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./run_tests.sh
        working-directory: ./tests
