name: tests

on:
  repository_dispatch:
#  schedule:
#    - cron: '0 15 1 1 0'
#  push:
#    paths:
#      - tests/**
#      - .github/workflows/tests.yml
#      - entrypoint.sh
#      - Dockerfile
#      - .dockerignore

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        run: shellcheck tests/*.sh

      - name: path
        run: which shellcheck

  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./run_tests.sh
        working-directory: ./tests
