name: Tests

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'
    branches:
    - master

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: shellcheck
      run: shellcheck tests/run.sh

  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: run tests
      run: ./run.sh
      working-directory: ./tests
