name: ubuntu-desktop

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/ubuntu-desktop.yml
      - ubuntu-desktop.json
      - Vagrantfile-linux.template
      - build.sh
      - templates/ubuntu.md
      - scripts/ubuntu/**
      - scripts/linux-common/**
      - http/ubuntu-desktop/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/ubuntu-desktop.yml
      - ubuntu-desktop.json
      - Vagrantfile-linux.template
      - build.sh
      - templates/ubuntu.md
      - scripts/ubuntu/**
      - scripts/linux-common/**
      - http/ubuntu-desktop/**

jobs:
  ubuntu-desktop:
    name: "*"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        stage:
          - ubuntu-20.04-desktop-amd64-virtualbox
          - ubuntu-18.04-desktop-amd64-virtualbox
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          brew install ansible coreutils gnu-sed packer

      - name: Build image - ${{ matrix.stage }}
        run: |
          export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:${PATH}
          ./build.sh ${{ matrix.stage }}

      - name: Check the created box image - ${{ matrix.stage }}
        run: |
          export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:${PATH}
          ./vagrant_init_destroy_boxes.sh /var/tmp/packer-templates-images/${{ matrix.stage }}.box
