name: Update Semver

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'

jobs:
  update-semver:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Semver
        uses: haya14busa/action-update-semver@v1
        with:
          github_token: ${{ secrets.github_token }}
