name: virt-check

on:
  repository_dispatch:
  # pull_request:
  #   types: [opened, synchronize]
  #   paths:
  #     - .github/workflows/virt-check.yml
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - .github/workflows/virt-check.yml

jobs:
  virt-check-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: lspcu
        run: |
          set -x
          lscpu
          egrep -o '(vmx|svm)' /proc/cpuinfo | sort | uniq
          egrep -wo 'vmx|lm|aes' /proc/cpuinfo  | sort | uniq | sed -e 's/aes/Hardware encryption=Yes (&)/g' -e 's/lm/64 bit cpu=Yes (&)/g' -e 's/vmx/Intel hardware virtualization=Yes (&)/g'


  virt-check-mac:
    runs-on: macos-latest
    steps:
      - name: sysctl
        run: |
          set -x
          sysctl kern.hv_support
          sysctl -a | grep machdep.cpu.features
          sysctl -a | grep -o VMX
