name: virt-check

on:
  repository_dispatch:
  # schedule:
  #   - cron: '0 15 1 1 0'
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/virt-check.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/virt-check.yml

jobs:
  virt-check-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: lspcu
        run: |
          set -eux
          lscpu
          egrep -o '(vmx|svm)' /proc/cpuinfo | sort | uniq
          egrep -wo 'vmx|lm|aes' /proc/cpuinfo  | sort | uniq | sed -e 's/aes/Hardware encryption=Yes (&)/g' -e 's/lm/64 bit cpu=Yes (&)/g' -e 's/vmx/Intel hardware virtualization=Yes (&)/g'
          # apt list --installed
          # dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get remove -y '^ghc-8.*'
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell
          sudo apt-get autoremove -y
          sudo apt-get clean
          rm -rf /usr/share/dotnet/
          df -h


  virt-check-mac:
    # runs-on: macos-11.0
    runs-on: macos-latest
    steps:
      - name: sysctl
        run: |
          set -x
          df -h /
          sysctl kern.hv_support
          sysctl -a | grep machdep.cpu.features
          sysctl -a | grep -o VMX
          df -h /
          brew uninstall openjdk gcc go php gradle gcc@8 gcc@9 azure-cli ant maven selenium-server-standalone aspell mongodb-community mongodb-database-tools aws-sam-cli python@3.8 icu4c cmake node@14 guile helm postgresql
          df -h /
          set +x
          # ( for pkg in `brew list --formula -1 | egrep -v '\.|\.\.'`; do echo $pkg `brew info $pkg | egrep '[0-9]* files, ' | sed 's/^.*[0-9]* files, \(.*\)).*$/\1/' | awk '{print $1;}/[0-9]$/{s+=$1};/[mM][bB]$/{s+=$1*(1024*1024);next};/[kK][bB]$/{s+=$1*1024;next} END { suffix=" KMGT"; for(i=1; s>1024 && i < length(suffix); i++) s/=1024; printf "\t(all versions: %0.1f%s)",s,substr(suffix, i, 1), $3; }'`; done ) | sort -k2
          # echo "********************"
          brew install findutils
          brew list --formula | xargs -n1 -P8 -I {} \
            sh -c "brew info {} | egrep '[0-9]* files, ' | sed 's/^.*[0-9]* files, \(.*\)).*$/{} \1/'" | \
            sort -h -r -k2 - | column -t | grep MB | sort -k2 -g
