name: virt-check

on:
  repository_dispatch:
  # schedule:
  #   - cron: '0 15 1 1 0'
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/virt-check.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/virt-check.yml

jobs:
  virt-check-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: lspcu
        run: |
          set -x
          df -h
          lscpu
          egrep -o '(vmx|svm)' /proc/cpuinfo | sort | uniq
          egrep -wo 'vmx|lm|aes' /proc/cpuinfo  | sort | uniq | sed -e 's/aes/Hardware encryption=Yes (&)/g' -e 's/lm/64 bit cpu=Yes (&)/g' -e 's/vmx/Intel hardware virtualization=Yes (&)/g'
          apt list --installed


  virt-check-mac:
    runs-on: macos-11.0
    steps:
      - name: sysctl
        run: |
          set -x
          df -h
          sysctl kern.hv_support
          sysctl -a | grep machdep.cpu.features
          sysctl -a | grep -o VMX
