name: vuepress-build-check-deploy

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/vuepress-build-check-deploy.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/vuepress-build-check-deploy.yml

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          exclude: |
            CHANGELOG.md

  markdown-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run mdspell
        run: find . -type f \( -name "*.md" ! -name "CHANGELOG.md" \) | xargs --max-args=1 --verbose mdspell --ignore-numbers --ignore-acronyms --report --en-gb

  vuepress-build-check-deploy:
    runs-on: ubuntu-latest
    needs:
      - markdownlint-check
      - markdown-spell-check
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Check broken links
        env:
          INPUT_URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}
          INPUT_PAGES_PATH: .
          INPUT_CMD_PARAMS: --buffer-size=8192 --max-connections=10 --skip-tls-verification --exclude=(myexample.dev|mylabs.dev|https://github.com/ruzickap/k8s-flux-repository)
        run: |
          echo ${INPUT_URL}
