name: yamllint-checks

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  yamllint-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: yamllint
        uses: karancode/yamllint-github-action@master
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
